### PR TITLE
Add Postgres support

### PR DESCRIPTION
**Pull request by Ant59**
- Add engine switch to command
- Add support for Postgres schema syntax
- Leverage Postgres enum types
- Leverage Postgres array types

### CODE REVIEW

**Comment by ZeldaZach** [comment]
Hey mate, thanks so much for the PR! I'm gonna check this out tomorrow most likely, but I hope to have it merged by end of week if it works as expected :)

**Review by ZeldaZach — APPROVED** [review]

**Comment by tooomm** [comment]
Why got this change reverted? Was there an issue?

**Comment by JoaoPPinto** [comment]
I'm also interested in why this got reverted. Is there anything that can be done to get this feature back in?

**Comment by ZeldaZach** [comment]
Hey there @JoaoPPinto and @tooomm it was reverted because it broke the SQL outputs. I'm currently working on a new system to generate SQL-agnostic code for y'all, just a bit slower than I'd like. If you want to help out, feel free to jump on the Discord (https://mtgjson.com/discord) as I'd love to chat :)

**Pull request merged**
